name: Build & Deploy GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Build
        run: |
          npm i yarn
          yarn install
          yarn build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          repo: aiogram/aiogram.github.io
          fqdn: aiogram.dev
          build_dir: dist
          keep_history: true
          target_branch: master
          committer_email: ci@aiogram.dev
          committer_name: GitHub Actions
          commit_message: Build of ${{ github.repository }}#${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
